[package]
name = "subkey"
version = "2.0.0-rc3"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
node-runtime = { version = "2.0.0-rc3", path = "../../node/runtime" }
node-primitives = { version = "2.0.0-rc3", path = "../../node/primitives" }
sc-cli = { version = "0.8.0-rc3", path = "../../../client/cli" }
frame-utilities-cli = { version = "2.0.0-rc3", features = ["balances"], path = "../../../utils/frame/frame-utilities-cli" }
structopt = "0.3.14"

[features]
bench = []
