[package]
name = "sp-tracing"
version = "2.0.0-rc5"
license = "Apache-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Instrumentation primitives and macros for Substrate."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-std = { version = "2.0.0-rc5", path = "../std", default-feature = false}
#sp-runtime-interface = { version = "2.0.0-rc5", path = "../runtime-interface", default-feature = false}
codec = { version = "1.3.1", package = "parity-scale-codec", default-features = false}
sp-externalities = { version = "0.8.0-rc5", optional = true, path = "../externalities" }
tracing = { version = "0.1.13", optional = true, default-features = false }
tracing-core = { version = "0.1.11", optional = true, default-features = false }
log = { version = "0.4.8", optional = true }
once_cell = { version = "1.4.0", optional = true }

[features]
default = [ "std" ]
with-tracing = [
    "tracing",
    "tracing-core",
    "codec/derive",
    "codec/full",
    "sp-externalities",
    "once_cell",
]
std = [
    "with-tracing",
    "tracing/std",
    "tracing-core/std",
    "codec/std",
    "codec/derive",
    "sp-std/std",
#    "sp-runtime-interface/std",
    "sp-externalities",
    "log",
]
