[package]
name = "sp-tracing"
version = "2.0.0-rc5"
license = "Apache-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Instrumentation primitives and macros for Substrate."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { version = "1.3.1", package = "parity-scale-codec", optional = true, default-features = false}
tracing = { version = "0.1.13", optional = true, default-features = false }
tracing-core = { version = "0.1.11", optional = true, default-features = false }
rental = { version = "0.5.5", optional = true }
log = { version = "0.4.8", optional = true }

[features]
default = [ "std" ]
with-tracing = [
    "tracing",
    "tracing-core",
    "codec",
    "codec/derive",
    "codec/full",
]
std = [
    "with-tracing",
    "tracing/std",
    "tracing-core/std",
    "codec/std",
    "rental",
    "log"
]
